"""IRT calibration.

The synthetic recovery check comes first and is non-negotiable: generate
responses from *known* item parameters, run the fitter, and see whether it
finds them again. Only a fitter that passes that is allowed near the real bank
— otherwise "calibrated" would mean nothing more than "a number came out of an
optimiser".
"""

from __future__ import annotations

import random

import numpy as np
import pytest

from probe.belief.calibration import (
    CalibrationReport,
    ItemFit,
    _apply_quarantine,
    _pack,
    _unpack,
    calibrate_bank,
    calibrate_competency,
)
from probe.belief.grm import sample_score
from probe.models import GRMParams

TRUE_ITEMS = {
    "q0": (0.8, [-1.8, -0.7, 0.3, 1.4]),
    "q1": (1.4, [-1.2, -0.4, 0.5, 1.6]),
    "q2": (2.0, [-1.5, -0.5, 0.6, 1.7]),
    "q3": (1.1, [-2.0, -0.9, 0.1, 1.1]),
    "q4": (1.7, [-0.9, -0.2, 0.7, 1.9]),
    "q5": (2.3, [-1.4, -0.6, 0.4, 1.5]),
}


def synthesise(n_respondents: int, seed: int = 20260807):
    """Responses drawn from the true parameters and a standard-normal ability
    distribution — the same population prior the fitter assumes."""
    rng = random.Random(seed)
    nprng = np.random.default_rng(seed)
    responses: dict[str, dict[str, int]] = {}
    for i in range(n_respondents):
        theta = float(np.clip(nprng.normal(0.0, 1.0), -2.9, 2.9))
        responses[f"r{i:04d}"] = {
            qid: sample_score(theta, a, b, rng) for qid, (a, b) in TRUE_ITEMS.items()
        }
    return responses


# ---------------------------------------------------- parameterisation


def test_pack_unpack_round_trips():
    for a, b in TRUE_ITEMS.values():
        got_a, got_b = _unpack(_pack(a, b))
        assert got_a == pytest.approx(a, abs=1e-6)
        assert got_b == pytest.approx(b, abs=1e-6)


def test_unpacking_always_produces_increasing_thresholds():
    """The optimiser works unconstrained, so the *parameterisation* has to make
    an invalid item unrepresentable rather than merely discouraged."""
    rng = np.random.default_rng(0)
    for _ in range(300):
        _a, b = _unpack(rng.normal(0, 3, size=5))
        assert all(b[i] < b[i + 1] for i in range(3))


# ------------------------------------------------------ synthetic recovery


def _fit_known(n_respondents: int, seed: int):
    return calibrate_competency(
        synthesise(n_respondents, seed=seed),
        {qid: GRMParams(a=1.0, b=[-1.5, -0.5, 0.5, 1.5]) for qid in TRUE_ITEMS},
    )[0]


@pytest.mark.slow
@pytest.mark.gate
def test_fitter_recovers_known_parameters():
    """The gate PLAN.md sets: `a` within +-0.2 and `b` within +-0.3 on at least
    90% of items, fitted from responses generated by known parameters.

    Run at 2500 respondents. That is a statement about the *estimator*, not
    about this project's calibration sample: at 800 the sampling error on `a`
    for a six-item set already reaches 0.27 on some seeds and 0.12 on others,
    which would make the gate a coin flip on the seed rather than a check on
    the fitter. (That is exactly how this test first failed, and chasing it as
    though it were bias cost an optimiser swap that changed nothing.) The real
    bank is fitted from 36 respondents and the resulting imprecision is handled
    by the quarantine rule rather than pretended away.
    """
    fits = _fit_known(2500, seed=20260807)

    a_ok = b_ok = 0
    for qid, (true_a, true_b) in TRUE_ITEMS.items():
        fit = fits[qid]
        a_ok += abs(fit.a - true_a) <= 0.2
        b_ok += max(abs(np.array(fit.b) - np.array(true_b))) <= 0.3

    assert a_ok / len(TRUE_ITEMS) >= 0.90, (
        "discrimination recovery: "
        + ", ".join(
            f"{q}: true {TRUE_ITEMS[q][0]:.2f} fitted {fits[q].a:.2f}" for q in TRUE_ITEMS
        )
    )
    assert b_ok / len(TRUE_ITEMS) >= 0.90


@pytest.mark.slow
def test_discrimination_estimates_are_unbiased_across_seeds():
    """The stronger claim, and the one that actually distinguishes a correct
    fitter from a subtly wrong one.

    A biased estimator would push the mean error consistently one way no matter
    the seed. Overestimating `a` is the dangerous direction: an
    over-discriminating item looks more informative than it is, which would
    flatter every downstream efficiency number.
    """
    errors = []
    for seed in (1, 2, 3, 4):
        fits = _fit_known(1200, seed=seed)
        errors.extend(fits[qid].a - true_a for qid, (true_a, _b) in TRUE_ITEMS.items())

    mean_error = float(np.mean(errors))
    assert abs(mean_error) < 0.10, f"systematic bias in discrimination: {mean_error:+.3f}"


@pytest.mark.slow
def test_recovered_discrimination_ordering_is_preserved():
    """Even where the point estimates wobble, the fitter must rank items by
    discrimination correctly — that ordering is what the policy exploits."""
    from scipy import stats

    fits, _i, _c = calibrate_competency(
        synthesise(800), {qid: GRMParams(a=1.0, b=[-1.5, -0.5, 0.5, 1.5]) for qid in TRUE_ITEMS}
    )
    true_a = [TRUE_ITEMS[q][0] for q in TRUE_ITEMS]
    fitted_a = [fits[q].a for q in TRUE_ITEMS]
    rho, _p = stats.spearmanr(true_a, fitted_a)
    assert rho >= 0.8, f"discrimination ordering rho={rho:.3f}"


def test_fitter_does_not_touch_ground_truth():
    """Marginal maximum likelihood integrates ability out against a population
    prior. Nothing in the signature can accept theta_star, which is what makes
    the calibrated bank an honest instrument rather than a lookup of the
    answers."""
    import inspect

    signature = inspect.signature(calibrate_competency)
    assert "theta" not in " ".join(signature.parameters)
    source = inspect.getsource(calibrate_competency)
    assert "theta_star" not in source


# ------------------------------------------------------------- quarantine


@pytest.mark.parametrize(
    ("fit", "expected"),
    [
        (ItemFit("q", a=0.1, b=[-1, 0, 1, 2], n_responses=100, converged=True, log_likelihood=0), True),
        (ItemFit("q", a=9.0, b=[-1, 0, 1, 2], n_responses=100, converged=True, log_likelihood=0), True),
        (ItemFit("q", a=1.5, b=[-1, 0, 1, 2], n_responses=5, converged=True, log_likelihood=0), True),
        (ItemFit("q", a=1.5, b=[-9, -8, 7, 9], n_responses=100, converged=True, log_likelihood=0), True),
        (ItemFit("q", a=1.5, b=[-1, 0, 1, 2], n_responses=100, converged=True, log_likelihood=0), False),
    ],
)
def test_quarantine_rules(fit, expected):
    _apply_quarantine(fit)
    assert fit.quarantined is expected
    if expected:
        assert fit.reason


def test_uninformative_items_are_quarantined_not_deleted():
    """Deleting them would hide that they were ever authored. The quarantined
    fraction is reported alongside every results table."""
    report = CalibrationReport(
        fits={
            "a": ItemFit("a", 1.5, [-1, 0, 1, 2], 100, True, 0.0),
            "b": ItemFit("b", 0.1, [-1, 0, 1, 2], 100, True, 0.0, quarantined=True, reason="a low"),
        }
    )
    assert report.quarantined == ["b"]
    assert report.quarantine_fraction == 0.5


@pytest.mark.slow
def test_quarantined_items_never_reach_eval(taxonomy):
    """The bank's `live()` view is the only thing policies draw from."""
    from probe.bank.generate import starter_bank

    bank = starter_bank(taxonomy)
    responses = {
        f"r{i}": {q.id: (i % 5) + 1 for q in bank.questions[:6]} for i in range(30)
    }
    calibrated, report = calibrate_bank(bank, responses, new_version="test")

    live_ids = {q.id for q in calibrated.live()}
    assert all(qid not in live_ids for qid in report.quarantined)
    # Items nobody administered must be quarantined, not silently kept at their
    # authoring defaults and passed off as calibrated.
    never_administered = [
        q for q in calibrated.questions if q.id not in {qq.id for qq in bank.questions[:6]}
    ]
    assert all(q.grm.quarantined for q in never_administered)


def test_calibrated_flag_distinguishes_fitted_from_authored(taxonomy):
    from probe.bank.generate import starter_bank

    bank = starter_bank(taxonomy)
    assert all(not q.grm.calibrated for q in bank.questions)

    # Realistic responses drawn from the items' own parameters. Feeding the
    # fitter degenerate data (every respondent scoring every item identically)
    # correctly produces quarantined items, which is a different test.
    subset = bank.questions[:3]
    rng = random.Random(4)
    nprng = np.random.default_rng(4)
    responses = {}
    for i in range(120):
        theta = float(np.clip(nprng.normal(0.0, 1.0), -2.9, 2.9))
        responses[f"r{i:03d}"] = {
            q.id: sample_score(theta, q.grm.a, q.grm.b, rng) for q in subset
        }

    calibrated, _report = calibrate_bank(bank, responses, new_version="test")
    fitted = [q for q in calibrated.questions if q.grm.calibrated]
    assert fitted, "nothing was marked calibrated"
    assert all(not q.grm.quarantined for q in fitted)


def test_degenerate_responses_are_quarantined(taxonomy):
    """Every respondent scoring every item identically carries no information
    about discrimination. The fitter must refuse rather than invent."""
    from probe.bank.generate import starter_bank

    bank = starter_bank(taxonomy)
    subset = bank.questions[:3]
    responses = {f"r{i}": {q.id: 3 for q in subset} for i in range(40)}
    _calibrated, report = calibrate_bank(bank, responses, new_version="test")
    assert all(report.fits[q.id].quarantined for q in subset)


def test_real_bank_is_calibrated_and_versioned():
    """The committed v2 bank must carry fitted parameters and say so."""
    from probe.bank.loader import load_bank

    bank = load_bank("v2")
    assert bank.version == "v2"
    live = bank.live()
    assert len(live) > 150, f"only {len(live)} live items after quarantine"
    assert all(q.grm.calibrated for q in live)
    quarantined = [q for q in bank.questions if q.grm.quarantined]
    assert all(q.grm.quarantine_reason for q in quarantined)
    assert len(quarantined) / len(bank.questions) < 0.25
