"""Bank persistence and the deterministic stub generator.

The bank is versioned and every results table names the version it was
computed against. Item parameters start as authoring defaults and are
overwritten by the Phase 3 calibration pass; ``GRMParams.calibrated`` records
which of the two a given item is carrying, so a results table can never
silently mix fitted and guessed difficulties.
"""

from __future__ import annotations

import json
from pathlib import Path

from probe.config import BANK_DIR
from probe.models import GRMParams, ProbeFamily, Question, QuestionBank, RubricAnchor
from probe.rubric.taxonomy import Taxonomy

#: Number of concepts a level-5 answer is expected to name. Chosen so the five
#: anchors are distinguishable without demanding an essay.
POOL_SIZE = 6

#: Cumulative concept counts required at each level. Level 1 requires nothing —
#: it is the "attempted, but named nothing correct" band.
LEVEL_THRESHOLDS: dict[int, int] = {1: 0, 2: 1, 3: 2, 4: 4, 5: 6}

#: Authoring defaults, deliberately uniform. Any structure in the fitted
#: parameters therefore comes from the data rather than from the seed.
DEFAULT_A = 1.0
DEFAULT_B = [-1.5, -0.5, 0.5, 1.5]

_STEMS: dict[ProbeFamily, str] = {
    ProbeFamily.SCENARIO: (
        "You are on call. {label} is implicated in a live problem: {hook}. "
        "Walk me through how you would think about it."
    ),
    ProbeFamily.TRADEOFF: (
        "Talk me through the trade-offs you weigh around {label_lower}. "
        "Concretely: {hook} — what would push you one way or the other?"
    ),
    ProbeFamily.DEBUG: (
        "A service is misbehaving and the evidence points at {label_lower}: {hook}. "
        "How do you narrow it down?"
    ),
    ProbeFamily.PAST_PROJECT: (
        "Tell me about a time {label_lower} mattered in something you built. "
        "In particular: {hook}."
    ),
}

_HOOKS: list[str] = [
    "latency on the p99 has tripled since Tuesday's deploy",
    "the numbers reconcile in staging but not in production",
    "the fix that worked last quarter made it worse this time",
    "two teams disagree about where the bug actually lives",
    "the obvious answer has already been tried and did not help",
    "you have one afternoon and no ability to reproduce it locally",
]

_DESCRIPTORS: dict[int, str] = {
    1: "Names none of the relevant ideas, or answers a different question.",
    2: "Names one relevant idea but does not connect it to the situation.",
    3: "Names the core ideas and applies at least one of them correctly.",
    4: "Names the core ideas plus a second-order consideration, and reasons about the interaction.",
    5: "Covers the full concept set including the failure modes, and states what would change the answer.",
}


def _rotate(items: list[str], by: int) -> list[str]:
    if not items:
        return []
    by %= len(items)
    return items[by:] + items[:by]


def build_question(
    *,
    competency_id: str,
    label: str,
    concepts: list[str],
    family: ProbeFamily,
    index: int,
    expected_seconds: float | None = None,
) -> Question:
    """One item, fully determined by its inputs.

    Determinism matters more than it looks: the bank is regenerated by
    ``make bank`` and a results table is only comparable across regenerations
    if item ids and concept pools are stable.
    """
    pool = _rotate(list(concepts), index)[:POOL_SIZE]
    hook = _HOOKS[index % len(_HOOKS)]
    text = _STEMS[family].format(label=label, label_lower=label[0].lower() + label[1:], hook=hook)

    anchors = [
        RubricAnchor(
            level=level,
            descriptor=_DESCRIPTORS[level],
            required_concepts=pool[: LEVEL_THRESHOLDS[level]],
        )
        for level in range(1, 6)
    ]
    # Debug and scenario probes take longer to answer than a trade-off prompt;
    # the policy divides EIG by this, so it is a real lever, not decoration.
    base = {
        ProbeFamily.SCENARIO: 110.0,
        ProbeFamily.TRADEOFF: 75.0,
        ProbeFamily.DEBUG: 120.0,
        ProbeFamily.PAST_PROJECT: 90.0,
    }[family]
    return Question(
        id=f"{competency_id}::{index}::{family.value}",
        competency_id=competency_id,
        probe_family=family,
        text=text,
        anchors=anchors,
        grm=GRMParams(a=DEFAULT_A, b=list(DEFAULT_B)),
        expected_seconds=expected_seconds if expected_seconds is not None else base,
    )


def stub_bank(
    taxonomy: Taxonomy,
    competency_ids: list[str] | None = None,
    per_competency: int = 2,
    version: str = "v0-stub",
) -> QuestionBank:
    """A deterministic bank with no model involved.

    Used by Phase 0 tests and by every fixture that needs items without caring
    what they say.
    """
    ids = competency_ids if competency_ids is not None else taxonomy.ids
    questions: list[Question] = []
    for cid in ids:
        node = taxonomy.get(cid)
        for i in range(per_competency):
            family = node.probe_families[i % len(node.probe_families)]
            questions.append(
                build_question(
                    competency_id=cid,
                    label=node.label,
                    concepts=node.concepts,
                    family=family,
                    index=i,
                )
            )
    return QuestionBank(version=version, taxonomy_version=taxonomy.version, questions=questions)


def bank_path(version: str) -> Path:
    return BANK_DIR / f"bank-{version}.json"


def save_bank(bank: QuestionBank, path: Path | None = None) -> Path:
    path = path or bank_path(bank.version)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(bank.model_dump(mode="json"), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return path


def load_bank(path_or_version: str | Path) -> QuestionBank:
    path = Path(path_or_version)
    if not path.exists():
        path = bank_path(str(path_or_version))
    return QuestionBank.model_validate_json(path.read_text(encoding="utf-8"))
